[project]
name = "payments-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "databases[postgresql]>=0.9.0",
    "fastapi[standard]>=0.118.0",
    "sqlalchemy>=2.0.43",
]
